version: '3.9'

services:
  djangoapp:
    container_name: chat-app
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./chatus:/chatus
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - .env
    depends_on:
      - psql
  psql:
    container_name: chat-db
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env